# config.py
SERVER_HOST = 'localhost'
SERVER_PORT = 12345
TILE_SIZE = 32
GRAVITY = 0.5
MAX_PLAYERS = 10

# Типы тайлов
TILE_AIR = 0
TILE_WALL = 1
TILE_FLOOR = 2
TILE_LAVA = 3
TILE_DEATH = 4
TILE_FINISH = 5
TILE_START = 6
TILE_HOOKABLE = 7
TILE_NOHOOK = 8